#!/usr/bin/env node

"use strict";

var app = require('express')(),
    express = require('express'),
    server = require('http').createServer(app),
    io = require('socket.io').listen(server),
    fs = require('fs'),
    when = require('when'),
    sequence = require('sequence');

server.listen(10364);
app.use("/images", express.static(__dirname + "/images"));
app.use("/static", express.static(__dirname + "/static"));

app.get('/', function (req, res) {
    res.sendfile(__dirname + '/index.html');
});

app.get('/client', function (req, res) {
    res.sendfile(__dirname + '/client.html');
});

io.sockets.on('connection', function(socket){
	socket.on('trigger', function(data){
		socket.broadcast.emit('trigger', data);
	})
})


